version: '3'

services:
  frontend:
    build: .
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    networks:
      - journey-track

networks:
  journey-track:
    external: true